package ui

/**
 * Compile-time mirrors of the Android `Colors` / `Icons` / `TextStyles` constant natives.
 * Bodies never run; only the signatures must match the real classes.
 */

private fun nope(): Nothing =
    throw UnsupportedOperationException("Velo UI natives are only available on the Android host")

@Suppress("unused", "FunctionName")
class Colors {
    fun primary(): String = nope()
    fun onPrimary(): String = nope()
    fun primaryContainer(): String = nope()
    fun onPrimaryContainer(): String = nope()
    fun secondary(): String = nope()
    fun onSecondary(): String = nope()
    fun secondaryContainer(): String = nope()
    fun onSecondaryContainer(): String = nope()
    fun tertiary(): String = nope()
    fun onTertiary(): String = nope()
    fun tertiaryContainer(): String = nope()
    fun onTertiaryContainer(): String = nope()
    fun error(): String = nope()
    fun onError(): String = nope()
    fun errorContainer(): String = nope()
    fun onErrorContainer(): String = nope()
    fun background(): String = nope()
    fun onBackground(): String = nope()
    fun surface(): String = nope()
    fun onSurface(): String = nope()
    fun surfaceVariant(): String = nope()
    fun onSurfaceVariant(): String = nope()
    fun surfaceContainer(): String = nope()
    fun outline(): String = nope()
    fun outlineVariant(): String = nope()
}

@Suppress("unused", "FunctionName")
class Icons {
    fun add(): String = nope()
    fun remove(): String = nope()
    fun menu(): String = nope()
    fun search(): String = nope()
    fun settings(): String = nope()
    fun home(): String = nope()
    fun favorite(): String = nope()
    fun favoriteBorder(): String = nope()
    fun star(): String = nope()
    fun info(): String = nope()
    fun check(): String = nope()
    fun checkCircle(): String = nope()
    fun close(): String = nope()
    fun clear(): String = nope()
    fun delete(): String = nope()
    fun edit(): String = nope()
    fun share(): String = nope()
    fun back(): String = nope()
    fun forward(): String = nope()
    fun more(): String = nope()
    fun person(): String = nope()
    fun account(): String = nope()
    fun notifications(): String = nope()
    fun refresh(): String = nope()
    fun email(): String = nope()
    fun phone(): String = nope()
    fun play(): String = nope()
    fun pause(): String = nope()
    fun cart(): String = nope()
    fun warning(): String = nope()
    fun done(): String = nope()
    fun list(): String = nope()
    fun send(): String = nope()
    fun lock(): String = nope()
    fun location(): String = nope()
    fun thumbUp(): String = nope()
    fun date(): String = nope()
    fun dropdown(): String = nope()
}

@Suppress("unused", "FunctionName")
class TextStyles {
    fun displayLarge(): String = nope()
    fun displayMedium(): String = nope()
    fun displaySmall(): String = nope()
    fun headlineLarge(): String = nope()
    fun headlineMedium(): String = nope()
    fun headlineSmall(): String = nope()
    fun titleLarge(): String = nope()
    fun titleMedium(): String = nope()
    fun titleSmall(): String = nope()
    fun bodyLarge(): String = nope()
    fun bodyMedium(): String = nope()
    fun bodySmall(): String = nope()
    fun labelLarge(): String = nope()
    fun labelMedium(): String = nope()
    fun labelSmall(): String = nope()
}
